version: "3.9"

services:
  node_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_server
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGDATABASE=${PGDATABASE}
    ports:
      - 3000:3000
  postgres_db:
    image: postgres:16.3-alpine3.20
    container_name: app_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 10
    restart: always
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres_pass
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
    ports:
      - 5444:5432
    volumes:
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
